=== iesanagonzalez/XMLRep/modulo/modulo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd">
	
	<xs:element name="Modulo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Nombre" type="xs:string" />
				<xs:element name="Contidos" type="tipoContidos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="tipoContidos">
		<xs:sequence>
			<xs:element name="Bloque" type="tipoBloque" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoBloque">
		<xs:sequence>
			<xs:element name="Titulo" type="xs:string" />
			<xs:element name="Descripcion" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== iesanagonzalez/XMLRep/modulo/modulo.xml
<?xml version="1.0" encoding="UTF-8"?>
 <Modulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="modulo.xsd">
       <Nombre>Redes de Area Local</Nombre>
       <Contidos>
             <Bloque>
                   <Titulo>Sistemas de comunicacins</Titulo>
                   <Descripcion>Aspectos físicos, protocolos e arquitecturas de redes.</Descripcion>
             </Bloque>
             <Bloque>
                   <Titulo>Redes de datos</Titulo>
                   <Descripcion>Dispositivos de interconexión de redes locais e de área extensa.</Descripcion>
             </Bloque>
             <Bloque>
                   <Titulo>Redes de área local</Titulo>
                   <Descripcion>Administración e xestión dunha rede de área local.</Descripcion>
             </Bloque>
             <Bloque>
                   <Titulo>Servizos Internet</Titulo>
                   <Descripcion>Adm. de servizos que empreguen protocolos estándar en Internet.</Descripcion>
             </Bloque>
       </Contidos>
 </Modulo>
 <!--
	Modificación: Añadir dos atributos a Bloque: numero y evaluacion (1,2,3)
 -->
